# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 483ce25aade083626f69aafb78dee5cdc9eaf55cdd4dbae62f57763a26c15c69af778b565f9c49d08ce1550cb48c4a4b9956d4e23687c5ca87734aaa03397a74

test:
  secret_key_base: ae2c6094fd151a31b0f80c067c940a949f26cec45c82e7f057707a4877d227f2cd22b5e734675fba5b905130f04239a82e422d6a5882d1cbaa0ee69a726a05fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
